# Azure Pipelines YAML - Auto-trigger on main branch

trigger:
  branches:
    include:
      - main # Jab bhi main branch me push ho, pipeline run ho

pool:
  vmImage: "ubuntu-latest" # Hosted agent VM

steps:
  - task: Checkout@1
    displayName: "Checkout repository"

  # Example build step (adjust according to your project)
  - script: echo "Building the project..."
    displayName: "Build Step"

  # Example test step (adjust according to your project)
  - script: echo "Running tests..."
    displayName: "Test Step"

  # Example deploy step (adjust according to your project)
  - script: echo "Deploying application..."
    displayName: "Deploy Step"
