trigger:
- main

pool:
  name: Default   # self-hosted agent pool

variables:
  imageName: 'alimuhammad9291/clientorbitapp'  # Docker Hub username + repo
  tag: 'latest'

steps:
- task: Docker@2
  displayName: 'Login to Docker Hub'
  inputs:
    command: login
    containerRegistry: 'DockerHubConnection'   # exact service connection name

- task: Docker@2
  displayName: 'Build Docker Image'
  inputs:
    command: build
    Dockerfile: '**/Dockerfile'
    tags: |
      $(imageName):$(tag)

- task: Docker@2
  displayName: 'Push Docker Image'
  inputs:
    command: push
    containerRegistry: 'DockerHubConnection'
    tags: |
      $(imageName):$(tag)
