trigger:
- main

pool:
  name: Default   # self-hosted agent pool

variables:
  imageName: 'alimuhammad9291/clientorbitapp'   # <-- your Docker Hub username + repo
  tag: 'latest'

steps:
- task: Docker@2
  displayName: 'Login to Docker Hub'
  inputs:
    command: login
    containerRegistry: 'DockerHub'   # exact service connection name

- task: Docker@2
  displayName: 'Build Docker Image'
  inputs:
    command: build
    Dockerfile: '**/Dockerfile'
    tags: |
      $(imageName):$(tag)   # this ensures proper tag

- task: Docker@2
  displayName: 'Push Docker Image'
  inputs:
    command: push
    containerRegistry: 'DockerHub'   # must include service connection
    tags: |
      $(imageName):$(tag)
