trigger:
  - main          # Auto-trigger on main branch

pool:
  name: Default   # Agent pool

variables:
  imageName: "alimuhammad9291/clientorbitapp"
  tag: "latest"

steps:
  - task: Docker@2
    displayName: "Build and Push Docker Image"
    inputs:
      containerRegistry: "DockerHubConnection" # exact service connection name
      repository: "alimuhammad9291/clientorbitapp"
      command: "buildAndPush"
      Dockerfile: "**/Dockerfile"
      tags: "$(tag)"
