trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  imageName: clientorbitapp  # Docker image name

steps:
  - task: Checkout@1
    inputs:
      clean: true
    displayName: 'Checkout source code'

  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run build
    displayName: 'Build React/Vite app'

  - task: Docker@1
    displayName: 'Build and Push Docker Image'
    inputs:
      containerRegistry: 'ClientOrbitDockerHub'  # Docker Hub service connection
      repository: 'clientorbitapp'
      command: 'buildAndPush'
      dockerFile: 'Dockerfile'  # root me Dockerfile
      tags: |
        latest
