trigger:
- main  # ya aapki branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'myapp'
  tag: 'latest'

steps:
# 1️⃣ Checkout the code
- task: Checkout@1
  displayName: 'Checkout repository'

# 2️⃣ Login to Docker Hub using service connection
- task: Docker@2
  displayName: 'Login to Docker Hub'
  inputs:
    command: login
    containerRegistry: 'DockerHub'  # <- ye aapke service connection ka exact name
    # username/password automatically use hoga service connection se

# 3️⃣ Build Docker image
- task: Docker@2
  displayName: 'Build Docker Image'
  inputs:
    command: build
    Dockerfile: '**/Dockerfile'
    tags: |
      $(imageName):$(tag)

# 4️⃣ Push Docker image to Docker Hub
- task: Docker@2
  displayName: 'Push Docker Image'
  inputs:
    command: push
    tags: |
      $(imageName):$(tag)
